version: '3.1'
services:
  client:
    build: ./App
    ports:
    - 19000:19000
    - 19001:19001
    - 19002:19002
    networks:
    - backend
    environment:
    - REACT_NATIVE_PACKAGER_HOSTNAME=${EXPO_HOSTNAME}
    - EXPO_ANDROID_KEYSTORE_PASSWORD=f0e4a1dfc3ab4113a3fcd0ea69a71dd0
    - EXPO_ANDROID_KEY_PASSWORD=08074ea1cd1141d3b3acaed7602d9ff6
    - EXPO_USERNAME=${EXPO_USER}
    - EXPO_PASSWORD=${EXPO_PASSWORD}
    command: sh -c "expo login -u ${EXPO_USER} -p ${EXPO_PASSWORD} && expo start --android -s ${EXPO_TEST}" # | expo build:android -t apk" #| expo build:android" # && expo build:android" # && expo start -s ${EXPO_TEST} && expo publish && expo url:apk"
    #expo export --dev --public-url http://127:8080 --force && npx http-server -p 8000 dist" # | turtle build:android --keystore-path /App/Mobile.jks --keystore-alias QGtpdHN1bmVrb3lhbWEvTW9iaWxl" #&& curl http://sv:8080/android-index.json"
    volumes:
    - apk:/apk/
  web:
    build: ./web
    ports:
    - 8081:80
    depends_on:
    - sv
    links:
    - sv
    networks:
    - backend
    volumes:
    - apk:/apk/
  db:
    build: ./db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    - 3306:3306
    networks:
    - backend
    volumes:
    - db-data:/var/lib/mysql
  sv:
    build: ./Server
    depends_on:
    - db
    command: bash -c 'while !</dev/tcp/db/3306; do sleep 5; done; npm start'
    environment:
      DATABASE_HOST: db
    ports:
    - 8080:8080
    networks:
    - backend
networks:
  backend:
volumes:
  db-data:
  apk: